version: '3'
services:
  label:
    image: "apps_label:latest"
    #    build: ./label
    container_name: "label"
    restart: always
    ports:
      - "8081:8081"
      - "8084:8084"
    volumes:
      - "/home/code/docker_ai/datasets_models:/home/code/docker_ai/datasets_models"
      - "/apps/label/logs:/apps/label/logs"
    environment:
      - PROFILE: prod
    depends_on:
      - "xxl-job-admin"
      - "mysql"
  mysql:
    image: "mysql:5.7.28"
    container_name: "mysql"
    ports:
      - "8082:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456#@
    volumes:
      - "/apps/mysql:/app/mysql/data"
  xxl-job-admin:
    image: "xuxueli/xxl-job-admin:2.1.0"
    container_name: "xxl-job-admin"
    restart: always
    ports:
      - "8083:8080"
    environment:
      PARAMS: '--spring.datasource.url=jdbc:mysql://50.56.88.11:8082/xxl-job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=root --spring.datasource.password=123456#@'
    volumes:
      - "/apps/xxl-job:/data/applogs"
    depends_on:
      - "mysql"
  minio:
    image: "minio/minio"
    container_name: "minio"
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /apps/minio:/data
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123.!
  nginx:
    image: "nginx:latest"
    container_name: "nginx"
      restart: always
      ports:
        - "8889:8888"
        volumes:
          - "/apps/nginx/nginx.config:/etc/nginx/nginx.conf"
          - "/apps/webapps:/home/html"